version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - .env
    ports:
      - "5005:5000"
    volumes:
      - ${UPLOADS_DIR}:/app/uploads
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
